SpECTRE: Surfaces
Surfaces
Namespaces
StrahlkorperTags
Holds tags and ComputeItems associated with a Strahlkorper.
StrahlkorperGr
Contains functions that depend both on a Strahlkorper and a metric.
Classes
class Strahlkorper< Frame >
A star-shaped surface expanded in spherical harmonics.
Functions
template<typename Frame >
tnsr::i< DataVector, 3, Frame > StrahlkorperGr::unit_normal_one_form (const tnsr::i< DataVector, 3, Frame > &normal_one_form, const DataVector &one_over_one_form_magnitude) noexcept
Computes normalized unit normal one-form to a Strahlkorper.
template<typename Frame >
tnsr::ii< DataVector, 3, Frame > StrahlkorperGr::grad_unit_normal_one_form (const tnsr::i< DataVector, 3, Frame > &r_hat, const DataVector &radius, const tnsr::i< DataVector, 3, Frame > &unit_normal_one_form, const tnsr::ii< DataVector, 3, Frame > &d2x_radius, const DataVector &one_over_one_form_magnitude, const tnsr::Ijj< DataVector, 3, Frame > &christoffel_2nd_kind) noexcept
Computes 3-covariant gradient \(D_i S_j\) of a Strahlkorper's normal.
template<typename Frame >
Scalar< DataVector > StrahlkorperGr::expansion (const tnsr::ii< DataVector, 3, Frame > &grad_normal, const tnsr::I< DataVector, 3, Frame > &unit_normal_vector, const tnsr::II< DataVector, 3, Frame > &upper_spatial_metric, const tnsr::ii< DataVector, 3, Frame > &extrinsic_curvature) noexcept
Expansion of a Strahlkorper. Should be zero on apparent horizons.
Detailed Description
Things related to surfaces.
Function Documentation
expansion()
template<typename Frame > Scalar< DataVector > StrahlkorperGr::expansion (const tnsr::ii< DataVector, 3, Frame > & grad_normal, const tnsr::I< DataVector, 3, Frame > & unit_normal_vector, const tnsr::II< DataVector, 3, Frame > & upper_spatial_metric, const tnsr::ii< DataVector, 3, Frame > & extrinsic_curvature) noexcept
Expansion of a Strahlkorper. Should be zero on apparent horizons.
Details
Implements Eq. (5) in https://arxiv.org/abs/gr-qc/9606010. The input argument grad_normal is the quantity returned by StrahlkorperGr::grad_unit_normal_one_form, and unit_normal_vector is \(S^i = g^{ij} S_j\) where \(S_j\) is the unit normal one form.
References gr::extrinsic_curvature(), and StrahlkorperGr::unit_normal_one_form().
grad_unit_normal_one_form()
template<typename Frame > tnsr::ii< DataVector, 3, Frame > StrahlkorperGr::grad_unit_normal_one_form (const tnsr::i< DataVector, 3, Frame > & r_hat, const DataVector & radius, const tnsr::i< DataVector, 3, Frame > & unit_normal_one_form, const tnsr::ii< DataVector, 3, Frame > & d2x_radius, const DataVector & one_over_one_form_magnitude, const tnsr::Ijj< DataVector, 3, Frame > & christoffel_2nd_kind) noexcept
Computes 3-covariant gradient \(D_i S_j\) of a Strahlkorper's normal.
Details
See Eqs. (1–9) of https://arxiv.org/abs/gr-qc/9606010. Here \(S_j\) is the (normalized) unit one-form to the surface, and \(D_i\) is the spatial covariant derivative. Note that this object is symmetric, even though this is not obvious from the definition. The input arguments r_hat, radius, and d2x_radius depend on the Strahlkorper but not on the metric, and can be computed from a Strahlkorper using ComputeItems in StrahlkorperTags. The input argument one_over_one_form_magnitude is \(1/\sqrt{g^{ij}n_i n_j}\), where \(n_i\) is StrahlkorperTags::NormalOneForm (i.e. the unnormalized one-form to the Strahlkorper); it can be computed using (one over) the magnitude function. The input argument unit_normal_one_form is \(S_j\),the normalized one-form.
References StrahlkorperGr::unit_normal_one_form().
unit_normal_one_form()
template<typename Frame > tnsr::i< DataVector, 3, Frame > StrahlkorperGr::unit_normal_one_form (const tnsr::i< DataVector, 3, Frame > & normal_one_form, const DataVector & one_over_one_form_magnitude) noexcept
Computes normalized unit normal one-form to a Strahlkorper.
Details
The input argument normal_one_form \(n_i\) is the unnormalized surface one-form; it depends on a Strahlkorper but not on a metric. The input argument one_over_one_form_magnitude is \(1/\sqrt{g^{ij}n_i n_j}\), which can be computed using (one over) the magnitude function.
Referenced by StrahlkorperGr::expansion(), and StrahlkorperGr::grad_unit_normal_one_form().